#!/bin/bash

if [ -f ~/.Xresources ]; then
	xrdb -merge ~/.Xresources
fi

if [ -f ~/.Xmodmap ]; then
	xmodmap ~/.Xmodmap
fi

if [ -x /usr/local/bin/external_display ]; then
	/usr/local/bin/external_display
fi

# wallpaper
~/.fehbg &

# compositor
picom -b

exec dbus-run-session i3
